sudo: false

language: java

jdk:
- oraclejdk8

before_deploy:
  - git config --local user.name "nabbl"
  - git config --local user.email "dakappler@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "target/*.jar"
  skip_cleanup: true
