sudo: false

language: java

jdk:
- oraclejdk8

before_deploy:
  - git config --local user.name "travis"
  - git config --local user.email "noreply@sourcepole.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - mvn package

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  on:
    branch: release
