sudo: false

language: java

jdk:
- oraclejdk8

before_deploy:
  - git config --local user.name "travis"
  - git config --local user.email "noreply@sourcepole.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - mvn package

deploy:
  provider: releases
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: AzEWnaAB9Mp+7viDOKXErQ3uLdesY/Hh29gI1ZI6AFlk35nklhODRNDYMSECD1/QBuLuIfKjGlL+GwsgsENophpEzaVArPOoOTIUgfxihM07ggtTIlG7HeQWXNtOlOEqeMYvoSbVlpaSDGf/ZfN/ZC1pHMBorR2YsLDu0XDdRr96Kjei8jmHLmKnCijR8zMXpPL4OFaqcXYoHBTLbdUxooERjRG/L0q5wSxP2ULIyWDHF5v09uXe3/C7ZsJJckFtEML0Dg/bF28kRtoRbnxM1Nbwjkt01eL3s40N/rnNsFsZkIqsj0d+5jgittWfDX1Uc5ccIQRV7XBg1z9JD8skdH750o4iUHjX5rtgu3fz2HoSoVqMhm9UWE3Sg9SaCFJBkLS2+3T6NaYMO8XyrZy/OzUiztx2WHWHXXs+KL+XmO+YSpco4n1bth1Dp5+bgQbOrX0/M8Zmp0k3+A8vWB5UMxMcI93UGAVmmkzakQMstzT8DnlhWF7o+ihctRfcOHMx4CoZCOAQY7uqhYqkLUUKs18mkpbw845m7yEFP/1TgoU68/eTRayhG5AxgC6i+FdE8spKHN4s3gjWYBjBYWXZGDhEIa6KGvWGl23S6Fc0NHXHqI8AZS7bPn0MJyySsMx6SY23eWNmMaFhV1Q3B4UHpBkmP3vg9/4aUX6jnBXfw7w=
